### ISSUE TITLE
Issues with Charitable Progress Circle...

### ISSUE THREAD

**Issue by cshschargerband** [Charitable/charitable-progress-circle#1]
A couple issues...
1. After adding the plugin, the progress circle pushes the content of the campaign page width and it no longer fits on page body.  There are a bunch of references to width in both the php and js code.
Thoughts?
![image](https://user-images.githubusercontent.com/70517243/91714148-bd0edb80-eb50-11ea-86b4-6e094f21684d.png)

2. The code from the link below causes a critical error when trying to round the percent donated.
library/campaigns/round-percent-donated-to-whole-number.php

**Comment by ericnicolaas** [comment]
@cshschargerband I just updated the plugin. I wasn't able to replicate the second issue you mentioned, but did tweak how the percentage is shown, so that may resolve the problem.
